In [200]:
#v2: Matriz con orden de movimientos (1,2,3, .., 9). Impares son X, pares son O.  0's son sin poner nada
#La etiqueta ahora distingue entre X o O. La misma puede ser 0, 1 o 2   (0-Empate, 1-gano X, 2-gano O)

In [201]:
import numpy as np
from copy import copy, deepcopy

listaPartidas = []  
listaEtiquetas = []

def HayGanador(tablero):
    #Recibe un Tablero,
    #retorna:   0 si nadie esta ganando, 1 si cruz y 2 si circulo
    result = 0
    
    #filas
    if (not(tablero[0,0]==0 or tablero[0,1]==0 or tablero[0,2]==0)) and (tablero[0,0]%2 == tablero[0,1]%2 == tablero[0,2]%2 == 1):
        result = 1
    if (not(tablero[0,0]==0 or tablero[0,1]==0 or tablero[0,2]==0)) and (tablero[0,0]%2 == tablero[0,1]%2 == tablero[0,2]%2 == 0):
        result = 2       
    if (not(tablero[1,0]==0 or tablero[1,1]==0 or tablero[1,2]==0)) and (tablero[1,0]%2 == tablero[1,1]%2 == tablero[1,2]%2 == 1): 
        result = 1
    if (not(tablero[1,0]==0 or tablero[1,1]==0 or tablero[1,2]==0)) and (tablero[1,0]%2 == tablero[1,1]%2 == tablero[1,2]%2 == 0): 
        result = 2     
    if (not(tablero[2,0]==0 or tablero[2,1]==0 or tablero[2,2]==0)) and (tablero[2,0]%2 == tablero[2,1]%2 == tablero[2,2]%2 == 1):
        result = 1
    if (not(tablero[2,0]==0 or tablero[2,1]==0 or tablero[2,2]==0)) and (tablero[2,0]%2 == tablero[2,1]%2 == tablero[2,2]%2 == 0):
        result = 2    
    
    #columnas
    if (not(tablero[0,0]==0 or tablero[1,0]==0 or tablero[2,0]==0)) and (tablero[0,0]%2 == tablero[1,0]%2 == tablero[2,0]%2 == 1):
        result = 1
    if (not(tablero[0,0]==0 or tablero[1,0]==0 or tablero[2,0]==0)) and (tablero[0,0]%2 == tablero[1,0]%2 == tablero[2,0]%2 == 0):
        result = 2       
    if (not(tablero[0,1]==0 or tablero[1,1]==0 or tablero[2,1]==0)) and (tablero[0,1]%2 == tablero[1,1]%2 == tablero[2,1]%2 == 1):
        result = 1
    if (not(tablero[0,1]==0 or tablero[1,1]==0 or tablero[2,1]==0)) and (tablero[0,1]%2 == tablero[1,1]%2 == tablero[2,1]%2 == 0):
        result = 2            
    if (not(tablero[0,2]==0 or tablero[1,2]==0 or tablero[2,2]==0)) and (tablero[0,2]%2 == tablero[1,2]%2 == tablero[2,2]%2 == 1):
        result = 1
    if (not(tablero[0,2]==0 or tablero[1,2]==0 or tablero[2,2]==0)) and (tablero[0,2]%2 == tablero[1,2]%2 == tablero[2,2]%2 == 0):
        result = 2    
        
    #diagonales
    if (not(tablero[0,0]==0 or tablero[1,1]==0 or tablero[2,2]==0)) and (tablero[0,0]%2 == tablero[1,1]%2 == tablero[2,2]%2 == 1):
        result = 1
    if (not(tablero[0,0]==0 or tablero[1,1]==0 or tablero[2,2]==0)) and (tablero[0,0]%2 == tablero[1,1]%2 == tablero[2,2]%2 == 0):
        result = 2         
    if (not(tablero[0,2]==0 or tablero[1,1]==0 or tablero[2,0]==0)) and (tablero[0,2]%2 == tablero[1,1]%2 == tablero[2,0]%2 == 1):
        result = 1    
    if (not(tablero[0,2]==0 or tablero[1,1]==0 or tablero[2,0]==0)) and (tablero[0,2]%2 == tablero[1,1]%2 == tablero[2,0]%2 == 0):
        result = 2    
    
    return result

def SiguienteMovimiento(tablero):
    #devolver max+1
    result = np.max(tablero) + 1
    return result

def JugarSiguiente(tableroPrevio):  
    tableroResult = tableroPrevio
    global listaPartidas
    
    
    #Algoritmo recursivo
    #Caso Base 1: si alguien ya gano. Agrego al set de datos y retorno
    #Caso Base 2: No hay ganador pero tampoco  hay movimientos posibles. Agrego al set de datos y retorno
    #Si no aplica ningun caso base, tomo un movimiento y hago llamado recursivo
    
    #Caso Base 1: si alguien ya gano
    ganador = HayGanador(tableroResult)
    if (ganador == 1) or (ganador == 2):
        #print(tableroResult)
        listaPartidas.append(deepcopy(tableroResult))
        listaEtiquetas.append(ganador)
        return tableroResult
    
    #Caso Base 2: no quedan movimientos posibles
    if ((tableroResult[tableroResult==0].size) ==0):
        #al no quedar movimientos posibles y no haber ganador, esta partida es empate.
        #print(tableroResult)
        listaPartidas.append(deepcopy(tableroResult))
        listaEtiquetas.append(0)
        return tableroResult
        
    elif (ganador==0):
        for fila in range(3):
            for columna in range(3):
                if tableroResult[fila,columna] == 0:
                    tableroResult[fila,columna] = SiguienteMovimiento(tableroResult)
                    tableroResult = JugarSiguiente(tableroResult)
                    tableroResult[fila,columna] = 0
    
    return tableroResult

def GenerarPartidas():
    global listaPartidas
    print("Comenzando a iterar, deberia dar un total de: 255168")
    cuenta = 0
    for fila in range(3):
        for columna in range(3):
            cuenta = cuenta + 1
            print("iteracion " + str(cuenta) + " de 9", end="\r") 
            
            tablero = np.matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
            tablero[fila,columna] = 1
            
            tablero = JugarSiguiente(tablero)
    
    print("")    
    print("Se terminaron de generar partidas, total:" + str(len(listaPartidas)))




In [202]:
import numpy as np
tablero = np.matrix([[1, 6, 0], 
                     [3, 2, 0], 
                     [0, 4, 5]])


#HayGanador(tablero)


GenerarPartidas()




Comenzando a iterar, deberia dar un total de: 255168
iteracion 9 de 9
Se terminaron de generar partidas, total:255168


In [203]:
print(listaPartidas[3645])
print(listaEtiquetas[3645])

[[1 2 7]
 [6 0 5]
 [0 4 3]]
1


In [211]:
import random

print(len(listaPartidas))
print(len(listaEtiquetas))


ratio_train = 0.90
len_train = round(len(listaPartidas)*ratio_train)


train_set = listaPartidas[1:len_train:1]
train_labels = listaEtiquetas[1:len_train:1]

test_set = listaPartidas[len_train+1:len(listaEtiquetas)-1:1]
test_labels = listaEtiquetas[len_train+1:len(listaEtiquetas)-1:1]


print(len(train_set))
print(len(train_labels))

print(len(test_set))
print(len(test_labels))

255168
255168
229650
229650
25515
25515


In [212]:
import keras
keras.__version__

'2.2.4'

In [213]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(9, activation='relu', input_shape=(3 * 3,)))
network.add(layers.Dense(9, activation='relu'))
network.add(layers.Dense(9, activation='relu'))
network.add(layers.Dense(3, activation='softmax'))

In [214]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [215]:
train_set = np.squeeze(np.asarray(train_set))
train_set = train_set.reshape((len(train_set), 3 * 3))
train_set = train_set.astype('float32') / 9

test_set = np.squeeze(np.asarray(test_set))
test_set = test_set.reshape((len(test_set), 3 * 3))
test_set = test_set.astype('float32') / 9

In [216]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [217]:
network.fit(train_set, train_labels, epochs=10, batch_size=128)

Epoch 1/10
229650/229650 [==============================] - 2s 8us/step - loss: 0.8360 - acc: 0.5267
Epoch 2/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.4033 - acc: 0.7978
Epoch 3/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.3608 - acc: 0.8000
Epoch 4/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.3412 - acc: 0.8143
Epoch 5/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.3334 - acc: 0.8180
Epoch 6/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.3305 - acc: 0.8191
Epoch 7/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.3279 - acc: 0.8192
Epoch 8/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.3234 - acc: 0.8215
Epoch 9/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.3180 - acc: 0.8252
Epoch 10/10
229650/229650 [==============================] - 1s 5us/step - loss: 0.3163 - a

In [218]:
test_loss, test_acc = network.evaluate(test_set, test_labels)
print('test_acc:', test_acc)

25515/25515 [==============================] - 0s 17us/step
test_acc: 0.840015677050378
